name: Build Node.js

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: 'Set up env'
      run: |
        sudo apt update
        sudo apt install gcc g++ linux-headers-$(uname -r) make

    - name: Start build
      run: |
        mkdir /home/runner/work/action/action/target
        wget https://nodejs.org/dist/v16.16.0/node-v16.16.0.tar.gz
        tar -zxf node-v16.16.0.tar.gz
        cd node-v16.16.0
        # Fix build script's bug
        sed -i "s/'-static'/'-static', '-Wl,--whole-archive', '-lpthread', '-Wl,--no-whole-archive'/" configure.py
        ./configure --fully-static --enable-static --prefix=/home/runner/work/action/action/target
        make -j 4 && make install
        cd /home/runner/work/action/action

    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: nodejs16
        path: target
